# About
title: Data Rights Finder
description: Find, understand and use information from privacy policies
url: https://www.datarightsfinder.org
licence_name: Open Database License
licence_url: https://opendatacommons.org/licenses/odbl/1.0/
contact_email: contact@datarightsfinder.org

# Images
favicon: /public/images/favicon.png
apple_touch_icon: /public/images/apple_touch_icon.png

# Social media
use_facebook_meta_tags: true
use_twitter_meta_tags: true
facebook_card_image: https://www.datarightsfinder.org/public/images/twitter-fb-card-1.png
twitter_card_image: https://www.datarightsfinder.org/public/images/twitter-fb-card-1.png
twitter_card_handle: ""

# GitHub
repository_path: datarightsfinder/data
user_agent: datarightsfinder/website

# Design
disable_mobile_menu: false
